### ISSUE TITLE
Program Configuration error

### ISSUE THREAD

**Issue by sunfic** [MicrochipTech/cryptoauthlib#143]
I designed a device on RPi platform with  ATSHA204A. when I try to run the sample configuration python program I got error for writing.
 
The command line: 
`python config.py -i i2c -p slave_address=0xC8`

output: 
```

Configuring the device with an example configuration


Serial number: 
    01 23 EE 3A C7 BF D4 5B EE

Reading the Lock Status
    Config Zone: Unlocked
    Data Zone: Unlocked

Getting the I2C Address
    Current Address: C8

Program Configuration

    New Address: C8
    Programming ATSHA204A Configuration
        Success
    Writen Configuration
    C8 00 55 00 8F 80 80 A1 82 E0 C4 F4 84 00 A0 85
    86 40 87 07 0F 00 C4 64 8A 7A 0B 8B 0C 4C DD 4D
    C2 42 AF 8F FF 00 FF 00 FF 00 FF 00 FF 00 FF 00
    FF 00 FF 00 FF FF FF FF FF FF FF FF FF FF FF FF
    FF FF FF FF 00 00 55 55
    Verifying Configuration
    C8 00 55 00 8F 80 80 A1 82 E0 C4 F4 84 00 A0 85
    86 40 87 07 0F 00 C4 64 8A 7A 0B 8B 0C 4C DD 4D
    C2 42 AF 8F FF 00 FF 00 FF 00 FF 00 FF 00 FF 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00
Traceback (most recent call last):
  File "config.py", line 242, in <module>
    configure_device(args.iface, args.device, args.i2c, args.gen, **parse_interface_params(args.params))
  File "config.py", line 160, in configure_device
    raise ValueError('Configuration read from the device does not match')
ValueError: Configuration read from the device does not match

```

It seems that all the bytes after 0x10 are 0. Dont know what caused this issue. Please suggest. 
Thanks

**Comment by sunfic** [comment]
I think I figured out. since ATSHA204A is a SHA device you have to run command as 

`python config.py -d sha -i i2c -p slave_address=0xC8`

However running this command in current version Release v3.1.0 (20200205) will yield this error: 
```
...
File "<string>", line 1, in <module>
NameError: name 'cfg_atsha204a_i2c_default' is not defined
```

check though the source code I found that previously "cfg_atsha204a_i2c_default" is defined but right now it is defined as "cfg_atsha20xa_i2c_default". I don't know why this define was changed but in order to fix the bug I change the testing python script `common.py` :
from 
`atca_names_map = {'i2c': 'i2c', 'hid': 'kithid', 'sha': 'sha204', 'ecc': 'eccx08'}`
to
`atca_names_map = {'i2c': 'i2c', 'hid': 'kithid', 'sha': 'sha20x', 'ecc': 'eccx08'}`

then the config program run as expected.

I will submit a fix on cryptoauthtools repo. better fix over there.

**Comment by sunfic** [comment]
cryptoauthtools repo updated. 
this is closed.
